name: Prettier action

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run Prettier
        run: yarn prettier
